import oracleLogo from "../../assets/oracle-com-logo.png";
import googleLogo from "../../assets/google-com-logo.png";
import metaLogo from "../../assets/meta-com-logo.png";
import awsLogo from "../../assets/aws-eu-logo.png";
import ibmLogo from "../../assets/ibm-com-logo.png";
import harvardLogo from "../../assets/harvard-edu-logo.png";
import courseraLogo from "../../assets/coursera-org-logo.png";
import edxLogo from "../../assets/edx-org-logo.png";
import sololearnLogo from "../../assets/sololearn-com-logo.png";
import udemyLogo from "../../assets/udemy-com-logo.png";
import umichLogo from "../../assets/umich-edu-logo.png";

// ── Row 1: Global Tech Giants & Industry Accreditation (Top Tier) ───────────
export const certificationsRow1 = [
  {
    id: "sololearn-python-intro",
    title: "Introduction to Python",
    issuer: "Sololearn",
    date: "Mar 2025",
    credentialId: "CC-RWXETJG7",
    url: "https://www.sololearn.com/certificates/CC-RWXETJG7",
    logo: sololearnLogo,
    skills: "Python Basics · Data Types · Logic",
    badge: "Skill Verified",
  },
  {
    id: "aws-cloud-essentials",
    title: "AWS Cloud Technical Essentials",
    issuer: "Amazon Web Services (AWS)",
    date: "Sep 2025",
    credentialId: "BZOJRUGYZI2Y",
    url: "https://www.coursera.org/account/accomplishments/records/BZOJRUGYZI2Y",
    logo: awsLogo,
    skills: "AWS EC2 · S3 · IAM · Cloud Security",
    badge: "Accredited",
  },
  {
    id: "oracle-java-17",
    title: "Oracle Certified Professional: Java SE 17 Developer",
    issuer: "Oracle",
    date: "Aug 2026",
    credentialId: "103502707",
    url: "https://catalog-education.oracle.com/pls/certview/sharebadge?id=5AFD796832F37D01BECB3FE71EF92C4E192D1297535504D6B26A1DE8007ABE99",
    logo: oracleLogo,
    skills: "Java SE 17 · Core Java · OOP Architecture",
    badge: "Official Certification",
  },
  {
    id: "google-agile-pm",
    title: "Agile Project Management",
    issuer: "Google",
    date: "May 2026",
    credentialId: "S7B9A8DACWSK",
    url: "https://www.coursera.org/account/accomplishments/records/S7B9A8DACWSK",
    logo: googleLogo,
    skills: "Scrum · Agile Delivery · Sprint Planning",
    badge: "Specialization",
  },
  {
    id: "meta-react-native",
    title: "React Native Specialization",
    issuer: "Meta",
    date: "Dec 2025",
    credentialId: "5GA8FKZ470DV",
    url: "https://www.coursera.org/account/accomplishments/verify/5GA8FKZ470DV",
    logo: metaLogo,
    skills: "React Native · Mobile Architecture · Cross-Platform",
    badge: "Specialization",
  },
  {
    id: "harvard-cs50-sql",
    title: "CS50: Introduction to Databases with SQL",
    issuer: "Harvard University",
    date: "Oct 2024",
    credentialId: "ac10e7b4-07fa-445f-bbb3-d09b163bf1a5",
    url: "https://certificates.cs50.io/ac10e7b4-07fa-445f-bbb3-d09b163bf1a5.pdf?size=letter",
    logo: harvardLogo,
    skills: "SQL · PostgreSQL · Normalization · SQLite",
    badge: "Harvard CS50",
  },
  {
    id: "ibm-python-ai",
    title: "Python for Data Science, AI & Development",
    issuer: "IBM",
    date: "Apr 2025",
    credentialId: "VXLVKFNC1Q7X",
    url: "https://www.coursera.org/account/accomplishments/verify/VXLVKFNC1Q7X",
    logo: ibmLogo,
    skills: "Python · REST APIs · Applied AI Pipelines",
    badge: "Professional Certificate",
  },
  {
    id: "ibm-node-express",
    title: "Developing Back-End Apps with Node.js & Express",
    issuer: "IBM",
    date: "Feb 2025",
    credentialId: "UZL6WXHFXHDT",
    url: "https://www.coursera.org/account/accomplishments/verify/UZL6WXHFXHDT",
    logo: ibmLogo,
    skills: "Node.js · Express.js · RESTful Services",
    badge: "Course Certificate",
  },
  {
    id: "meta-js-programming",
    title: "Programming with JavaScript",
    issuer: "Meta",
    date: "Jul 2024",
    credentialId: "LPHBTMQQU8L2",
    url: "https://www.coursera.org/account/accomplishments/records/LPHBTMQQU8L2",
    logo: metaLogo,
    skills: "JavaScript ES6+ · Testing with Jest · OOP",
    badge: "Course Certificate",
  },
  {
    id: "meta-react-basics",
    title: "React Basics",
    issuer: "Meta",
    date: "Mar 2025",
    credentialId: "3TH344WX8SBP",
    url: "https://www.coursera.org/account/accomplishments/verify/3TH344WX8SBP",
    logo: metaLogo,
    skills: "React.js · Components · Virtual DOM",
    badge: "Course Certificate",
  },
  {
    id: "meta-frontend-intro",
    title: "Introduction to Front-End Development",
    issuer: "Meta",
    date: "Feb 2024",
    credentialId: "FC8K8NTATVDY",
    url: "https://coursera.org/share/68406befba18dcda96afe93de3751e2f",
    logo: metaLogo,
    skills: "HTML5 · CSS3 · Responsive UI",
    badge: "Course Certificate",
  },
  {
    id: "udemy-fullstack-mern",
    title: "FullStack Web Development: Node, Express, Mongo",
    issuer: "Udemy",
    date: "Aug 2024",
    credentialId: "UC-1540c402-3092-4986-8b2c-9a9033217b25",
    url: "https://www.udemy.com/certificate/UC-1540c402-3092-4986-8b2c-9a9033217b25/",
    logo: udemyLogo,
    skills: "Node.js · Express · MongoDB · Full-Stack",
    badge: "Certificate of Completion",
  },
];

// ── Row 2: World Elite Universities & Systems Engineering (Top Tier) ───────
export const certificationsRow2 = [
  {
    id: "harvard-cs50x",
    title: "CS50x: Introduction to Computer Science",
    issuer: "Harvard University / CS50",
    date: "Oct 2023",
    credentialId: "359f2060-ff40-4bc6-94c9-a46217d65bf0",
    url: "https://certificates.cs50.io/359f2060-ff40-4bc6-94c9-a46217d65bf0.pdf?size=letter",
    logo: harvardLogo,
    skills: "C · Python · Data Structures · Memory Management",
    badge: "Harvard CS50",
  },
  {
    id: "polytechnique-doc-research",
    title: "Recherche Documentaire & Méthodologie",
    issuer: "École Polytechnique",
    date: "Apr 2025",
    credentialId: "UAPUPG8O91S5",
    url: "https://www.coursera.org/account/accomplishments/verify/UAPUPG8O91S5",
    logo: courseraLogo,
    skills: "Scientific Research · Technical Evaluation",
    badge: "Grandes Écoles",
  },
  {
    id: "epfl-cpp-oop",
    title: "Programmation Orientée Objet (C++)",
    issuer: "EPFL",
    date: "Dec 2024",
    credentialId: "b8db35384de054f13f9eb9af610977a1",
    url: "https://coursera.org/share/b8db35384de054f13f9eb9af610977a1",
    logo: courseraLogo,
    skills: "C++ · OOP Principles · Abstraction",
    badge: "EPFL Academic",
  },
  {
    id: "hkust-software-engineering",
    title: "Software Design & Project Management",
    issuer: "HKUST",
    date: "Apr 2025",
    credentialId: "NNFCOERJLJSC",
    url: "https://www.coursera.org/account/accomplishments/verify/NNFCOERJLJSC",
    logo: courseraLogo,
    skills: "Design Patterns · Software Engineering · UML",
    badge: "Academic Credential",
  },
  {
    id: "jhu-unix-workbench",
    title: "The Unix Workbench",
    issuer: "Johns Hopkins University",
    date: "Dec 2024",
    credentialId: "5289b44f84c7200fd85d0f1430fcb832",
    url: "https://coursera.org/share/5289b44f84c7200fd85d0f1430fcb832",
    logo: courseraLogo,
    skills: "Linux · Bash · Git · CLI Automation",
    badge: "University Credential",
  },
  {
    id: "umich-js-interactivity",
    title: "Interactivity with JavaScript",
    issuer: "University of Michigan",
    date: "Nov 2024",
    credentialId: "8ec75aaf19a413c1cd94882035d9b104",
    url: "https://coursera.org/share/8ec75aaf19a413c1cd94882035d9b104",
    logo: umichLogo,
    skills: "JavaScript · DOM Manipulation · Events",
    badge: "Academic Credential",
  },
  {
    id: "edx-cs50x",
    title: "edX Verified: CS50 Computer Science",
    issuer: "edX / HarvardX",
    date: "Nov 2023",
    credentialId: "c5c2c5e3515c4296af60d6a7e5bf1a5f",
    url: "https://courses.edx.org/certificates/c5c2c5e3515c4296af60d6a7e5bf1a5f",
    logo: edxLogo,
    skills: "Algorithms · Complexity · Security",
    badge: "Verified Certificate",
  },
  {
    id: "laravel-php-mastering",
    title: "Mastering Laravel Framework & PHP",
    issuer: "Board Infinity",
    date: "Feb 2025",
    credentialId: "KTS607O8Y4E5",
    url: "https://www.coursera.org/account/accomplishments/verify/KTS607O8Y4E5",
    logo: courseraLogo,
    skills: "Laravel · PHP 8 · Eloquent ORM · Blade",
    badge: "Specialization",
  },
  {
    id: "sololearn-cpp-intermediate",
    title: "C++ Intermediate",
    issuer: "Sololearn",
    date: "Sep 2024",
    credentialId: "CC-HQO6CONX",
    url: "https://www.sololearn.com/certificates/CC-HQO6CONX",
    logo: sololearnLogo,
    skills: "C++ Classes · Inheritance · Polymorphism",
    badge: "Skill Verified",
  },
  {
    id: "sololearn-cpp-intro",
    title: "Introduction to C++",
    issuer: "Sololearn",
    date: "Sep 2024",
    credentialId: "CC-XYPSMZVD",
    url: "https://www.sololearn.com/certificates/CC-XYPSMZVD",
    logo: sololearnLogo,
    skills: "C++ Syntax · Control Flow · Functions",
    badge: "Skill Verified",
  },
  {
    id: "udemy-js-essentials",
    title: "JavaScript Essentials",
    issuer: "Udemy",
    date: "Mar 2024",
    credentialId: "UC-908d65e0-be5e-41a5-8403-a39ff4ec0fd5",
    url: "https://www.udemy.com/certificate/UC-908d65e0-be5e-41a5-8403-a39ff4ec0fd5/",
    logo: udemyLogo,
    skills: "JavaScript Fundamentals · Modern Syntax",
    badge: "Certificate of Completion",
  },
];
